### ISSUE TITLE
rocm 6.4 and rocm 5.7 issues on linux

### ISSUE THREAD

**Issue by tuleo1** [advanced-lvl-up/Rx470-Vega10-Rx580-gfx803-gfx900-fix-AMD-GPU#10]
hello, sorry for another issue open im here to report on a few things related to this on gfx803 (rx 580) on linux (arch)

as you know rocm fully and completely dropped support for rx 580 but there are some dockers made that help to build and compile pytorch and rocblas pyvision and so on, for us
it has diffrent rocblas version from 5.4 to 6.4 and apparently and im not sure i havent tested they all supposedly work.

repo: https://github.com/robertrosenbusch/gfx803_rocm

the issue with this repo is that im trying to use the rocblas compiled here and given on the release page to see how good and better they are for comfyui.
however on docker rocm 6.4 i get ALWAYS noise for no reason. no matter what i use what i do and what i dont even stock rocblas gives me noise.
using your rocblas gives me a huge speed boost around 1 second less in the iteration per second. (6.5 -> 5.5 sdxl 1024x1024)

but i cant get it to work, idk why. noise all over for some reason.

so i tried 5.7 and it works i dont get noise anymore on stock rocblas libs but the issue now is that when i try to use your provided rocblas it instantly gives me this error:

"Memory access fault by GPU node-1 (Agent handle: 0x19c01de0) on address (nil). Reason: Page not present or supervisor privilege.
Aborted (core dumped)"

no matter what flag i use and what i dont use ex —lowvram —force-fp32 —force-fp16 no matter what they dont work.

SO with the big brain of mine i said "why not make a frankestine so it might help someone fix this!"

and now i have copied these types:
4xii8I
BB
BS
CC
DD
with copying those above the gen speed was "normal" the same as stock but the output was noise and all noise.
HH
HS
I8I
after copying these 3 my gen speed started going up from a simple "1.7s/it" to "6it/s" lol but i get noise so. and vram usage was reduced to 3gb idk why (im using this repo's jab attention implementation)

copying ZZ type also ended having same speed same noise and same vram usage nothing changed.

moving SS type starts giving the seg fault and maf error no matter what file from .hsaco or .co or .dat they all start giving seg faults.

idk if this helps or not but i hope it does.
hopefully a proper linux version will come out soon too.
i know this is out of this scope as its rocm and not zluda but i do hope you do check!

**Comment by tuleo1** [comment]
i will try to build rocblas with the files yaml and etc provided from this place to see if i can make it work on here!
will update if i succeed if not then yeah. nothing

**Comment by advanced-lvl-up** [comment]
No worries, this is a totally open forum, where you can talk about anything.   This will be another busy year for me without enough time, but i'm making yet another vow to crack this Linux issue.   If i wish it into existence then will it finally happen? 

Will look forward to your reports, and progress if any.   I think one possibility is that the library is incomplete, hence it will fall back to the ASM path and GEMMs if a Tensile contraction solution is not found for a particular call to ROCm.   This is fine since the ASM path is also fast and relatively optimized in the custom library, but perhaps that's why it doesn't work for you on Linux quite yet.  the core solution index code is based on the Tensile version 6.24 framework

I'll review overall compatibility issues and get back to you soon

**Comment by tuleo1** [comment]
no worries take your time dont burn yourself down. im surprised such project even exists since this gpu is quite old and many people just go "forget it just buy a new gpu"
so having any kind of support and help on this old gpu is HEAVILY appercieated!.

on other notes:
i tried building rocblas using the source you have put up in this repo and
everything seemed to be straight forward all i had to do was just replace the yaml files provided into "library/src/blas3/Tensile/Logic/asm_full"
and then do the cmake files to make rocblas
while doing so i got hit with an error:
AssertAIGreaterThanEqual was making issues in the file: polaris_Cijk_Alik_Bljk_SB - s1.yaml

so i just commented that one line and it went through.
and i used this command to build: ./install.sh -ida gfx803 -j 8 && \ true

and it built! but im not sure if its actually working or not... i used to go to build folder and use cmake manually to build but that kept giiving errors so  used the shell file there.
unsure if it worked or not and if im using your custom kernel codes to run my rocblas or no rn.

but it is working
testing with sdxl 1024x1024 eps model i get 7s/it with 6.3gb vram usage on —normalvram and using jab attention

no noise no issue vram usage seems fine the pictures are fine gpu is not heating too much and yeah!
my only worry is that maybe by using install.sh script or commenting out that one line of code made things not accurate or correct per say.
or maybe rocblas downloaded polaris libs and overrode the old ones. im just unsure.
but as long as it works?

ill update this with kobold.cpp token generation speed in a bit! after building it and we'll see how it will be :D

**Comment by advanced-lvl-up** [comment]
Thanks for that info :)  I'll leave out the AssertAIGreaterThanEqual in the next build if it makes zero difference to the Tensile compiler.  This particular option allows ROCm to choose kernels based on `AI`  (arithmetic intensity), and i think it's safe to ignore this one.  will confirm on the next build test.

Another thing you can try for specific Linux builds is to the change the:
`    WorkGroupMapping: -1`
`    WorkGroupMappingType: Z`

to:

`    WorkGroupMapping: 0`
`    WorkGroupMappingType: A`

(zero, and letter A,).   As this fix (in theory) is only required for Windows and adds extra code in the kernels, so for Linux it maybe faster and better to use hardware mapping, and default workgroup distribution.

**Comment by tuleo1** [comment]
will rebuild asap and report back!
im still stuck on building kobold lol

**Comment by advanced-lvl-up** [comment]
Great!  Also if `WorkGroupMappingType: A` causes memory leaks over time, another valid option is `B`
To be honest, though, i have no idea what effect it will have for Linux.  If all else fails i guess `Z` is fine too.

For kobold it likely won't help much, most LLM models end up using the `Cijk_Alik_Bljk_HB` contraction  (i don't remember if it was exactly that one.  but it was one of those i never got around to testing much)

Unfortunately tensile doesn't compile this one properly, and in the end we may need to use custom C++ code along with `asm volatile` to put some optimizations in there.  This was something i was working on last year.  We'll see.   i guess you never know til you try.  Maybe it actually works on Linux with no changes

**Comment by advanced-lvl-up** [comment]
But that's only related to speed.  Generally the contraction should at least run without crashing.  (hopefully, lol)

**Comment by tuleo1** [comment]
hey! so i built and used kobold cpp. there were two issues while building it. one was that on rocm before 6 in one of the functions you must've had put 3 variables instead of 2 which koboldcpp only had put 2 and i got that fixed.

in the file: 

> yourkoboldsource/ggml/src/ggml-cuda/ggml-cuda.cu

`CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event));`
to
`CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event, 0));`

and then another one which is:

`CUDA_CHECK(cudaStreamWaitEvent(cuda_ctx->stream(), concurrent_event->join_events[i - 1])); `
to
`CUDA_CHECK(cudaStreamWaitEvent(cuda_ctx->stream(), concurrent_event->join_events[i - 1], 0));`



and once those are done you have to also make another adjustment in your hip driver

> /opt/rocm-5.7.0/include/hip/amd_detail/amd_hip_bf16.h

and you must change every

` "__hostdevice__" -> "static __hostdevice__" `

and that will stop errors related to duplicate variable defined compilation error.


now that aside on my previous note i said i might have accidentally ended up using the old rocblas libs and not actually using the patched ones.

now im still uncertain but this time while building rocblas i installed stock ones and i found out that yes indeed the speed is 7s/it so nothing was diffrent

but this time as i recompiled i also pasted the folder r9nano as well previously i only have pasted Polaris
i also renamed Polaris to polaris and also had both of them there, as i saw that most of the folders there were not startinig as capital so i did that just in case. (had both Polaris and polaris there now)

and i also chanegd all those from Z to A and from -1 to 0 to all the files 
and after rebuilding and reinstalling and checking through sd woallah! i get 6s/it instead of the 7s/it! crazy

with kobold? honestly. i have zero idea if its faster or not. the way kobold is handling the token generation speed and token processing speed is extremely weird where if the text is larger the generation token per second is slower but when the text is small t/s is very high around 20t/s ?

i cant tell benchmarking is also out of the question cause everytime i use it the processing blas is FAR slower than what it actually is so generally its...weird lol.

also koboldcpp does seem to be working just fine. no issues or whatsoever either. only compilation errors because of rocm 5.7 which koboldcpp wasnt meant to be build on but we did.

comfyui is fire though <3

as for the memory leaks i havent tested neither am i sure on how to check for memory leaks in this context (perhaps by using the ai for long times. i havent had the chance to do that yet)
so if i do encounter them i will update

edit:
seems like something is wrong with the processing of tokens, im not sure whats up, the speed is extremely extremely slow. vulkan processed the tokens like rather quickly while using 170W
but rocblas? it took ten times the time it took vulkan to process and was using only 110W for some reason. something is off about it and im really unsure whats up.
ah while also rocm process the tokens my mouse and the pc ui just starts lagging? freezing periodically. unsure what to thnk of it?
perhaps memory issues freezes or errors in the kernel that keeps happening and it keeps going back to failsafe drivers. iim not sure.
if you know something i could use that would help ex logging more or something id be happy to try it

edit2:
the amount of clip or text you put inside your sd directly changes the speed of the it/s on the mage generation. why does this matter and why this is the case i have no idea.
i put around 252 characters on 13 steps on 512x512 i get 1.3-1.5s/it
and when i put 24296 characters (yes i know overwhelming) the speed went to 3.3s/it for the same resolution.

also while image generation i noticed the speed of iterations are quite unstable.
first step takes a long time 6s/it then second step instantly comes after. but the average is:
5.35s/it (on an overclocked 1430mhz 2000mhz rx580) 1024x1024 sdxl 1 lora

**Comment by advanced-lvl-up** [comment]
Wow, thanks.  the compiling tips will be quite useful for anyone if they run into similar issues in the future.   I've never bothered trying ROCm with Microsoft windows.  Simply just assumed that it would not work in windows at all.  :)

the sd.cpp backend that it uses can be really unstable for testing.  generally works better on native CUDA as far as i remember.  it's been way to long since i've tried.  no idea what the code looks like these days.

The strange thing i encountered was that (with zluda),  the speed would be exactly the same as with Vulkan... so i would then assume that it's silently falling back to Vulkan.   Except all the hardware monitoring indicates that it is in fact using zluda/CUDA.   I tried confirming if the Tensile kernels were indeed active.   Suffice to say:  it was all very confusing.  The mysteries are endless with that code.

My rather uninformed theory back then was simply the one i shared earlier about the particular kernel type `Cijk_Alik_Bljk_HB`,  and then i didn't explore much further than that.   For LLM's maybe we should try comfy nodes of some kind and force a particular data type to be used (if possible) , that way we'll have a clear idea of how native ROCm actually behaves.   Just an idea which i haven't tested or thought about much

**Comment by advanced-lvl-up** [comment]
Now as to the sd.cpp part dealing with image diffusion, i would assume they use the more standard fp16 kernels or similar. (depending on initial settings), so there's less mystery there.   It's definitely interesting that it actually worked for you at all.   (you can feel free to laugh at us windows users)  =)

edit:  i forgot to ask about the custom attention function.  I've been wondering about how it behaves in Comfy linux.  Is it slower?   Is the VRAM usage and tensor allocation acceptable?   if you find any bugs in there , i'll try to fix them if possible.

**Comment by tuleo1** [comment]
alright another day and another weird thing i just learnt. lol

once you told me to check the jab function i got surprised as i thought this was the most optimal way for this. and i suppose it is for something but for image generation?
well...okay vram usage is around 900mb less than "pytorch-cross-attention" when using jab i can use --normalvram in comfy without trouble and that makes my vram usage is 6.2gb on 1024x1024:

                           jab-attention

first gen:  5.55s/it               full time: 98s
second gen: 5.47s/it           full time: 84s

now for pytorch cross attention. when using it vram usage skyrockets. im not sure why. but when using i must use --lowvram so my cpu load goes 100% when it checks clip. on the same configuration same clip text and same resolution vram usage is 7.2gb and the gens are:

                           pytorch-attention

first gen: 4.54s/it               full time: 108s
second gen: 4.53s/it           full time: 72s

this is only if i dont switch clips though. when changing clips on the third generation things get a little weird.
(only changing the positive clip adding an extra word inside the prompt)

pytorch-atten: 4.52s/it               full time: 85s
jab-atten:5.47s/it               full time: 92s



seems like generally speaking pytorch attention despite more vram hungry is faster for generation, surprisingly it uses more power as well while generating, i see my gpu power throttling a lot while on jab it practically doesnt!

so pytorch. is faster but more vram hungry and for 1024x1024 it must be used with —lowvram


just for fun i also tested split-cross-attention and the original quad attention, here are the results:

                            split
first gen: 5.38s/it       fulltime: 95s
second gen: 5.47s/it  fulltime: 83s
third (diff prompt): 5.34s/it    fulltime:87s

                            quad
first gen: 5.36s/it       fulltime: 97s
second gen: 5.18s/it  fulltime: 80s
third (diff prompt): 5.23s/it    fulltime:88s

their vram usage are all identical to jab and yeah so is the power usage.

generally speaking for speed alone its like this right now:
pytorch>quad=jab>split

i couldnt test sage or flash as they require extra python package and i dont have them and i dont think they work on rocm 5.7.0



actually looking at the logs im seeing this glaring and annoying warning:
UserWarning: 1Torch was not compiled with memory efficient attention. (Triggered internally at /pytorch/aten/src/ATen/native/transformers/hip/sdp_utils.cpp:505.)

so...maybe actually im using no attention at all LMAO

edit:
by using --fp8_e5m2-text-enc you wont need --lowvram anymore :D

**Comment by advanced-lvl-up** [comment]
if you can get a `pytorch sdpa` or `sage / flash attn` working with a linux package, that would be your best bet.  (i have no idea if anyone has compiled such a package that works for older archs).  but if it exists, that would be much better.  even a partial implementation should be okay.

the benchmark data is very useful, thanks.  i think the results are what i would generally expect from the code.  There exists another version of `jab-attn` that's a bit faster somewhere in my archives.  For now it's mostly only useful for video gen or trying higher parameter models that we normally would not bother with.  (latent image and compute buffers will max out VRAM pretty much no matter what, in those cases).

Another thing it allows is using the comfy `--gpu-only` commandline option.  In past comfy versions, for example,  that would load both the UMT-T5-xxl encoder and the Wan 1.3billion model nicely into less than 7gb VRAM.   And as long as you didn't go above 512x512 times 81 frames, it would be fine i think.   It's useful for testing.  Not sure how this currently behaves in newer comfy.

The better option is dumping the UMT-T5 altogether, using saved prompt embeddings from disk.  Make a 1000 generic prompts ahead of time, and then just pick one that's close enough.  That way the text encoder never even loads :) lol

There are pull requests currently for better DRAM and VRAM management in comfy, but unfortunately that's going to take a while before it matures, especially the GGUF support.  But that's beauty of pytorch:  There is no memory management :)

We're basically stuck using either `--novram`,  or `--normal-vram`, or `--low-vram`, etcetera.    none of which are really optimal.

**Comment by tuleo1** [comment]
hi!
this isnt anything biggie honestly just wanted to say i tried and was able to successfully built pytorch 2.10 and vision 0.25 and triton 3.6.0 (despite it giving runtime errors saying my rocm is too old).
i was able to test and check and apparently pytorch is using the gpu the gpu is doing correct math ish im not sure 
but once it comes to comfyui suddenly all i get is noise :D
i have 0 idea why im getting noise. like the math is fine at least basic math is (GroupNorm, SiLU, attention, etc.) are working without NaN or Inf

so. honestly im out of clues. the image isnt...full white or full black so
i tried 2 diffrent  models same results but that was given as it was working on pytorch 2.3

the build wasnt fun to do so. it was horrible. literally everything about it sucked lots of issues in pytorch code where the code just refused to build properly i had to edit tons of stuff inside the code even some stuff inside my own driver believe it or not (in rocm i mean)
and then inevitably yeah.
hopefully someone anyone knows a way to fix this maybe? someone whos smarter than me in a way or two but im pretty sure anyone smart enough would just go and build rocm 6.4 and above and then build torch there.
or even they wont bother with this hardware xD.


now on a side note i found something very very very intresting. while testing for ways to remove or fix the noise i stumbled upon these flags:
export MIOPEN_DEBUG_DISABLE_FIND_DB=1 and export MIOPEN_FIND_ENFORCE=3

it takes a LONG time to build the database but once it's done (well...at least once or twice it worked!)
my speed went from 4.5s/it by using pytorch attention to 2.6s/it! a whopping double the performance almost i was so amazed by this.
but i tried to replicate this again and then....now its been 5 hours later and im still trying to replicate it. idk why but i cant get that speed boost anymore no matter what.
sometimes i get even worse performance eg 7s/it instead of 4.5 or 5s/it 
its weird...i dont know why. i hope you know something about this mayhaps?
it'd be cool if you end up looking through this or give us some information!.

also i found out that apparently this noise on pytorch 2.10 i get is the same noise i was getting in pytorch 2.4 in the rocm 6.4 docker.
which is making me wonder if this is the pytorch fault or not...or maybe hell maybe its comfyui's fault god knows! 

hopefully if someone has any information about this they would help or continue on this issue, im pretty determined about this and this silly hardware even if old its still gold and its proven now.

**Comment by advanced-lvl-up** [comment]
I think Lee, the owner of the fork https://github.com/lshqqytiger/ZLUDA, would be most qualified for that.  But then he's the quite busy person, i doubt he'd have to time to help us with such a niche request.    So, yea, we'd be on our own pretty much.  Maybe someone out there has something like that unpublished or something.  You never know, i guess.

If i had more time, i have would have tried (and likely failed) long ago.  

About the noise outputs issue,  if you're in Comfy,  i think near the time the Wan2.1 code was introduced, there was a major refactor of the comfyUI code near that time, which changed how default model loading and related data types worked.  It may be related to that, or maybe it has something to do with the recent changes the RMS_norm refactor.  (I'm just guessing here, no idea to be honest).

I only say that because comfyUI used to work much better for old GPU archs using pytorch==2.2.1  for example, like some zluda users do.  It's functional still, but some model architectures end up with non-optimal signal to noise after many transformer passes.  (Others like Wan Vace, and Wan2.2 5billion are fine though.)   Could be entirely unrelated as well.

I don't think i'd be brave enough to try what you're doing there. :)  that's awesome

**Comment by tuleo1** [comment]
ah youre flattering me.
im just stuck with this hardware like probably other people and im trying to squeeze as much performance as i can even for ai workload.

i might open a zluda issue but honestly i doubt its gonna go anywhere.
im more intrested in trying to build rocm 7.2 or 7.1 for our gpu but honestly? i dont have much hope seems like even searching for the name gfx803 on the newer rocm packages straight up give no result.

but if it would be possible things would be a lot easier.
on another note. im still trying the MIOpen optmization for my gpu, its so weird. sometimes the database is faster and sometimes the database is slower despite the same searches and look ups?
im still trying to reach the time where i got a whole 2.5-3s/it generation that was insane. but still nothing.
i do suggest you or others who might be reading this in the future to run it though as long as it exists for yall in windows xD
just put the flags and run your ai and it starts to test multiple diffrent ways to use the math on the gpu
its basically Nvidia CudNN but for our gpu. if only amd made these stuff more backwards compatible (newer version)

i might look into trying to use  other stable diffusion clones like a1111 and sdnext and some other ones. maybe they work fine?

after the MIOpen is done, what i noticed now that the speed is normal is that somehow the images look better?
as if the math of the model is being better accurately repersented in the gpu i dont even know man.
maybe its placebo but yeah

**Comment by advanced-lvl-up** [comment]
For me the tinkering part is more fun than actually using it for anything.  Maybe i'm just strange in that aspect.
much respect there, and it's fascinating that you managed to get so much of it working.

Now that i'm bored with machine learning (pretending AGI is near can be fun until the effect wears off), i'm not sure what to do hobby-wise.  I just wish i had more knowledge with pytorch to help with your build quest.  To me it just looks like an endless garden maze of code, and i feel as though jumping in would lead to machine elves and tricksters inside

**Comment by tuleo1** [comment]
that is true. i kinda gave up. i deleted everything related to newer clones and just. yeah

my ssd is taking a toll. 93% in only a year. i dont want it dying before i can get a new laptop especially since i live in iran and the prices are as high as a human's blood.

i failed. honestly, and well i dont mind it. sure generation speed is slow but at least i can make something.
and i truly understand what youe saying too its so fun to tinker with this stuff to get it to work. but i have a tendency to overwork myself and forget about responding to people or eating or anything x3 so yeah.

maybe ill visit this again later but for now yeah im fine with old pytorch and old rocm ill try to not delete this docker and export it just incase those repositories of rocm 5.7 end up getting deleted 

~~just for a refrence i found about a project thats quite cool called ROCK (https://github.com/ROCm/TheRock) its basically a script that builds everything the whole rocm package for you
but its a bit heavy a lot heavy. infact it broke my btrfs partition in linux and i had to run a balance command so it could fragment my ssd so i could finally start using my ssd again xD~~

has no script for gfx803! even if you get it downloaded and cloned the script probably will refuse to build for our gpu

also if you like this stuff a lot i recommend dual booting/running linux as a whole its a lot more fun!

**Comment by tuleo1** [comment]
found out how i got 2.5s/it
use pytorch attention! has better performance for now
use cfg 1.0 on comfyui it makes the clip instead of getting passed into the model every few steps in
it just passes it once at the beginning of the generation and then the gpu only just focused on generation.
even using cfg at 1.1 will break this
i suggest using sdxl models for this as they are relatievly okay for this.
:D have fun generating people!

**Comment by advanced-lvl-up** [comment]
excellent.  there are also reports right now of 6 secs per iteration in Z-image turbo using vulkan/mesa in linux.  while i dont know much about that myself, it's great seeing this, my favorite GPU arch, in action as always =)  i really don't keep up with all the model releases these days, haha

**Comment by chboishabba** [comment]
https://github.com/advanced-lvl-up/Rx470-Vega10-Rx580-gfx803-gfx900-fix-AMD-GPU/issues/9
https://github.com/robertrosenbusch/gfx803_rocm/issues/37
https://github.com/robertrosenbusch/gfx803_rocm/issues/43
https://github.com/robertrosenbusch/gfx803_rocm/issues/47

#AI : https://chatgpt.com/share/69af62e6-6724-8002-a58c-65e2b4cd0269

Some Polaris/Vega kernel regressions reported on LKML involve memory management paths used by ROCm (including XNACK-related page fault handling), which is another reason to test the same user-space stack on multiple host kernels before assuming the problem is purely in ROCm.

* Treat this as **two separate bugs**, not one: **diffusion/image-gen noise is most likely a MIOpen convolution/kernel-selection problem**, while **slow LLM/token throughput is most likely missing or fallback GEMM/Tensile coverage**; Whisper working on ROCm 6.4 is strong evidence that general HIP/PyTorch math is not the core failure. ([[rocm.docs.amd.com](https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com)][1])

* **Do not chase this first on Windows containers**; ROCm containers **share the host kernel/driver**, so they only make sense when the host driver stack is already suitable, and SD.Next still notes that **PyTorch ROCm on Windows is not officially maintained by the PyTorch team** in that workflow. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html?utm_source=chatgpt.com)][2])

* If they want the Rosenbusch route, use it as a **Linux or Linux-container test matrix**, not as “Windows magic”; his gfx803 work includes ROCm 6.3.4/6.4-era Dockerfiles specifically for Polaris/ComfyUI-style experiments, which is the right place to compare user-space combinations against the same host driver. ([[GitHub](https://github.com/robertrosenbusch/gfx803_rocm/?utm_source=chatgpt.com)][3])

* **Pin one known-good baseline first**: fixed model, fixed resolution, fixed prompt, fixed CFG, fixed attention backend, fixed precision, fixed kernel version, fixed MIOpen DB state; otherwise they are changing problem shape and autotune state at the same time, which MIOpen explicitly uses to select different kernels and cache entries. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com)][1])

* **Instrument before rebuilding**: run with `MIOPEN_ENABLE_LOGGING=1`, a high `MIOPEN_LOG_LEVEL`, and rocBLAS logging so they can see **which exact conv/GEMM kernels were selected** on a good run versus a noisy run; MIOpen’s own docs show that environment variables control tuning/search/perfdb behavior. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com)][1])

* **Yes, use a debugger, but only after logging narrows it down**: use `rocgdb`/`gdb` for crashes and GPU faults, and `rocprof`/profiling for the non-crashing “noise image” case; the first hard question to answer is still “which first layer or kernel produces bad values?” rather than “why is ROCm weird?” ([[ROCm Documentation](https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com)][1])

* Add **tensor sanity checks after each UNet stage** on one failing image-gen run: log min/max, mean/std, and NaN/Inf after the first conv, first resblock, first attention block, mid block, first upsample, and VAE decode; once the first corrupted tensor is found, they can map it back to the MIOpen or rocBLAS kernel actually launched.

* **Reset and control the MIOpen database deliberately**: MIOpen stores tuning/performance data and can be forced to search or reuse cached results, so inconsistent 2.6 s/it vs 7 s/it behavior is very plausibly “different perfdb entry / different exact problem config,” not randomness. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/MIOpen/en/develop/conceptual/perfdb.html?utm_source=chatgpt.com)][4])

* For image generation, test exactly three precision modes and stop speculating: **fp32 everywhere**, **fp16 weights + fp32 accum/vae**, and **their current mixed mode**; if only mixed precision is noisy, that immediately narrows it to unsupported or numerically unstable half-precision image kernels rather than general correctness.

* **Assume MIOpen conv kernels are the prime suspect until disproven**: Whisper is transformer-heavy, while diffusion hits conv/upsample/VAE paths much harder; MIOpen’s tuning/search docs are directly about those convolution paths, which matches the symptom split. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com)][1])

* **Assume slow token processing is fallback GEMM until disproven**: low power draw and UI lag are classic signs of poor occupancy and long blocking kernels rather than “the GPU is fast but mysterious”; compare kernel names and timings for one LLM prompt under ROCm versus Vulkan to see whether ROCm is missing the optimized contraction path.

* **Do not over-interpret equal ZLUDA and Vulkan speeds**; on old hardware they can converge simply because both end up on similarly limited matmul paths, so equal wall-clock time is not proof that one is secretly using the other.

* **Keep CFG at 1.0 only if the goal is throughput testing**, not image-quality comparison; classifier-free guidance changes compute shape materially, so it is a benchmark trick, not a general fix.

* **Treat JAB / split / quad / PyTorch attention as a speed-VRAM tradeoff, not a root-cause fix**; if the warning says memory-efficient attention was not compiled, they are mostly comparing fallback attention paths anyway, not unlocking flash-style kernels. ([[GitHub](https://github.com/vladmandic/sdnext/wiki/AMD-ROCm?utm_source=chatgpt.com)][5])

* **Do not expect official ROCm 6.x+ compatibility semantics for Polaris**: AMD officially dropped gfx803 years ago, and current ROCm compatibility documentation is for supported hardware, so every gfx803 result on modern ROCm should be treated as community salvage, not expected behavior. ([[GitHub](https://github.com/ROCm/ROCm/issues/1353?utm_source=chatgpt.com)][6])

* **Check the host kernel version before blaming user-space**: there are recent Polaris/gfx803 reports tying ROCm freezes under compute load to newer Linux kernels and amdkfd regressions, so a “bad ROCm build” may actually be “good user-space on a bad host kernel.” ([[OpenWall Lists](https://lists.openwall.net/linux-kernel/2025/06/25/2176?utm_source=chatgpt.com)][7])

* Use the Rosenbusch stack to build a **4-way matrix** only: **ROCm 5.7 vs 6.4** crossed with **stock vs patched rocBLAS/Tensile**, on the **same host kernel and same model**, then record correctness, first bad layer, selected MIOpen kernels, and token/s-it throughput; that will answer more than weeks of ad hoc tinkering.

* **Do not mix Windows ROCm, WSL ROCm, Linux ROCm, native ROCm, ZLUDA, and Vulkan in one troubleshooting loop**; AMD’s current Windows/WSL ROCm story exists, but it is its own compatibility matrix and not the same as native Linux Polaris salvage. ([[ROCm Documentation](https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installrad/wsl/install-radeon.html?utm_source=chatgpt.com)][8])

[1]: https://rocm.docs.amd.com/projects/MIOpen/en/develop/reference/env_variables.html?utm_source=chatgpt.com "MIOpen environment variables"
[2]: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html?utm_source=chatgpt.com "Running ROCm Docker containers"
[3]: https://github.com/robertrosenbusch/gfx803_rocm/?utm_source=chatgpt.com "General Site for the GFX803 ROCm Stuff ..."
[4]: https://rocm.docs.amd.com/projects/MIOpen/en/develop/conceptual/perfdb.html?utm_source=chatgpt.com "Using the performance database — MIOpen 3.5.1 ..."
[5]: https://github.com/vladmandic/sdnext/wiki/AMD-ROCm?utm_source=chatgpt.com "AMD ROCm · vladmandic/sdnext Wiki"
[6]: https://github.com/ROCm/ROCm/issues/1353?utm_source=chatgpt.com "Sad news, AMD drop offical supporting for gfx803 on ..."
[7]: https://lists.openwall.net/linux-kernel/2025/06/25/2176?utm_source=chatgpt.com "linux-kernel - Re: [REGRESSION] RX-580 (gfx803) GPU ..."
[8]: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installrad/wsl/install-radeon.html?utm_source=chatgpt.com "Install Radeon software for WSL with ROCm"

**Comment by advanced-lvl-up** [comment]
@chboishabba  hello, thanks for that.   it's quite interesting how GPT approaches it.

one of the problems encountered (while working with Windows) is that older pytorch and ROCm versions would always underutilize the GPU since `warp_size`, `mp_count` (multiprocessor count), and other parameters were designed for native CUDA.   The custom library here uses a simple work-around by assigning more work per GEMM call, and it isn't exactly the best way to do it, since register pressure goes a bit too high.  (https://github.com/Painter3000/AMD-GPU-BOOST/  has some code for tweaking the core parameters during GPU init.)

starting with ROCm 6.4 or above, using newer pytorch, most of this problem should be fixed (for later architectures at least), but i think this fundamental issue outlined above still applies on both Linux and Windows, especially for older archs. 

One of the AMD developers had an interesting response about this when github user Painter3000 mentioned it.  The dev said that in classic ROCm , the `mp_count` really related more to the workgroup distribution rather than actual compute units on the GPU, or something along those lines.  Wish i still had a link to the discussion.  it was fascinating.

As usual, i never dug into the archaic code all that seriously.  The actual fix shouldn't be all that difficult, but it takes time and understanding of the code.  5 hours is my limit before the boredom and laziness starts.  =)  So all my implmentations are about 20% to 30% done and mostly unfinished.

Recently, (year 2025 - 2026) LLMs have matured enought to code 70% of optimizations similar to this.  Personaly, when i interact with an LLM, i spend about 10% of the time talking about machine learning.  the rest of the time is just roleplay / pretending it's AGI, or asking about jokes and fun stuff (Qwen MAX is great for this).   I would guess most people are like that too =)    Why is it so much fun?   these days, i'm mostly at work and dealing with boring real-life stuff, unfortunately

**Comment by chboishabba** [comment]
Hi mate.. reckon I could probably have a go at updating anything if you're able to point me in the direction. You're right re GPT coding, it's gotten quite good. I helped submit a report to kfd last year re rx580 segfaults that got rolled in.

Just woke up but I'll come back to this.

Appreciate if anyone else feels like assisting.

**Comment by advanced-lvl-up** [comment]
great, if GPT or Claude gets stuck on something specific, let me know and i'll try to help if possible.  I'd most likely be useless to be honest becaues it been quite some time since i've dealt with the underlying mechanics of it all. 

Also, we can still pray that TheRock project converges with the original Linux builds soon.  I think that would clear up some of the issues of why some things work better in zluda while others work better in native ROCm.  Won't be holding my breath for that.   for gfx803 it might be faster (calendar time-wise) to try a ground-up approach with basically all general compatibility removed, focusing only the model type / architecture  (LLM, vision model, classification, etc) one would personally want to use. 🥇

**Comment by chboishabba** [comment]
Not sure what you mean re focus only on model type - they all require a stable setup. I am familiar with the 'noise' outputs some users were getting with Comfy but ostensibly the repo author had shown that it can produce proper outputs. It's also been a while since I was involved and likewise hope for Rock. I had contribbed testing there too before he got a job with AMD.

What probably would help though is some test harness where all the layer types can be tested. Should allow us to make some categorical statements about compatibility.

The main issue the community has been struggling with is KFD doorbell reset sometimes hard failing, unable to reset kfd/restart the card and hard crashes session (cannot recover to emergency terminal, hard reset only).

This was addressed around 6.16 iirc and solved one of the major points of instability beyond driver deprecation.

Do you have any logs of your work? I'm not familiar with the sort of meddling you had been up to...


Really the only thing for linux would seem to be those kernels/files/optimisations you made - segfaults otherwise. I don't think there is anything wrong with latest driver though, im on cachy latest and via the robertrosenbusch compatibility docker i'm able to compute. it's just the roc libs afaik and possibly compiling torch/ctranslate etc after...

**Comment by advanced-lvl-up** [comment]
right, i only meant it might be easier to try a very narrow (native gfx803) inference pipeline, with none of the baggage of ROCm and  pytorch's limited support for abandoned GPU archs, but assuming functionality only for very specific ML models or tasks.   I've had no time to keep up with all the recent changes to native Linux ROCm (still planning on trying at some point in time), so that part is mostly just guessing from my own viewpoint.

the optimization attempts i was tinkering with a few winters ago were mostly trying to get LLVM / Tensile and Windows ROCm 5.71 SDK (the only version that worked in microsoft OS at the time) to behave and function better with `zluda`.    You can see the results from that here on this github repo and, as you know, it's mostly half-finished and only useful for testing Windows.  Everything else is sort of incidentally related.  The actual test code and debug code is unreleased and buggy, i still remember much of it.  There aren't any logs, just scattered code fragments in my archives.

Now that TheRock project is bringing native support to Windows carried over from the original Linux builds, it may no longer even be necessary for my project to exist.  However, if it turns out that gfx803 will never be included in official Linux or modernized TheRock builds,  maybe then at that point i'll decide pick up the original goals again using either Linux or Windows, depending on which is easier to deal with.

i'll need to research this KFD issue that you mentioned when i have time. thank you, that seems quite informative!

**Comment by chboishabba** [comment]
I just had a thought - because we've found that vk implementations are equal/better speed (from memory vk did support bf16/fp16 on our hardware) if there's some way we can backtest against vk or use it to port missing kernels?

Can't remember if I mentioned but zluda was one of my early projects once we had the docker going. It would be interesting to see if the 6.4 dockers work for you via WSL... I can't recall if wsl uses windows' drivers...

I think AI should be able to put together something of a worklog from commits and those fragments if any of them made it here...

I have some hope that TheRock will/may help for gfx803 because of our previous contact. In the linux version it was merely a matter of adding the string 'gfx803' to the list of compile options in the CLI. If you do decide to have a poke, have a look at the original project ... I just tried to find it quickly and couldn't - I imagine it's probably been taken down. I reached out to who GPT thinks was the original author of the community one. If you decide to follow it up, let me know and I'll see if I can track down old posts of mine on tehre...


re KFD https://lists.freedesktop.org/archives/amd-gfx/2025-June/126663.html

**Comment by chboishabba** [comment]
Hmm I forgot they provide a build docker which could be helpful...

EDIT: Someone actually just posted in there, by recollection the repo is no longer maintained:

https://github.com/lamikr/rocm_sdk_builder
https://github.com/lamikr/rocm_sdk_builder/discussions/261#discussioncomment-15671890

gfx803 support:
https://github.com/lamikr/rocm_sdk_builder/issues/173

2024 steam hardware survey:

<img width="1481" height="1036" alt="Image" src="https://github.com/user-attachments/assets/8d2e3816-0432-4284-b7b0-72df9b893870" />

**Comment by advanced-lvl-up** [comment]
i love reading about such topics.  hah, imagine just casually mentioning GPU optimization during a dinner party of something. =)

there's a genetic condition called progeria, where a person can age 50 years before they reach their late teens.  I'm sort of the opposite of that, where as i only age in elf years.  It's both a blessing and curse, as one might imagine.  Aside from the strange looks you get from strangers, it can also lead to some rather painful experiences, to say the least.   In other words, i still look, feel and act like a teen even after my rather long trek in the world.  It's not exactly as bad as one might think.  For example, the ladies love it and find it endearing, so i can't complain too much honestly.  

one my ambitions when i was an actual kid, when i was sitting there with a CGA 4 color monitor on a random IBM clone PC, was to buy one of those shiny `ATI All-in-Wonder` graphics adapters, or something in that style.  those might have come along much later.  But we mostly used Atari, Sega MkIII, and NES during that time and didn't care much for PCs.  I eventually just went with the flow as Nvidia knocked 3Dfx out of the market and took over everything, and soon after was stuck with only Nvidia 'til recently.

quite some time ago, someone gifted me an rx580 that ended up untouched in my garage shelf for years.  Then much later, after hearing all the normies on popular media bashing AMD and saying its useless, (many of them were likely just Nvidia bag holders pumping their stock, most likely lol).  I decided to bring out the rx580 and test it for myself.  Don't regret it one bit, indeed it's quite  fine hardware.   And lo and behold, it's actually an ATI card... i didn't even realize it at the time i received it. hah.   So now you understand why i've taken an interest in such things.  Sorry for long and random personal story.  Suffice to say, it was really a dream come true in the classic sense.  I'm still using gfx803 even now, it so _feels_ like a real ATI card =)

It's rather sad that AMD abandoned these, and that Nvidia users decided to troll about it.  Otherwise, we'd likely have 100x the number of ATI nostalgia seekers on github to help with a native implementation, that could have already happened long ago in a different timeline.

**Comment by advanced-lvl-up** [comment]
@chboishabba I mentioned some debug and test code earlier, so here's a quick guide i've made for you, in case anyone wants try finishing the project on their own, or creating some kernels for personal use and testing.

This is a real-world example of the following kernel in particular  `polaris_Cijk_Alik_Bljk_HHS_BH_S1.yaml` from this github repo.
While i don't recommend that anyone actually try this, it could be a fun exercise for learning basic GPU code using gfx803.  Also, you could use it as a simple LLM coding benchmark test.  (be sure to prompt that it's a ROCm / Tensile kernel).  The LLM is always trained mostly on CUDA code, so giving it non-standard code like this is a great test of it's general knowledge!

When ROCm/Tensile loads a `.yaml` file, the automated compiler will emit what looks like thousands of lines of cryptic C++ code.
I've translated it into human (and LLM) readable text.  You can feed this into Claude / Kimi / GPT  if you get stuck on something.  This is basically like a Rosetta stone for non-programmers that should save a few weeks of learning introductory level things.

```
#define NUM_THREADS 256
#define SG0I 16      // Subgroup (wavefront) dim I
#define SG1J 16      // Subgroup dim J (16x16 = 256 threads)
#define TT0I 8       // Micro-tile I (registers)
#define TT1J 8       // Micro-tile J
#define MT0I 128     // Macro-tile I (per WG)
#define MT1J 128     // Macro-tile J
#define UNROLL 16     // Unroll iterations
#define LDS_SIZE (128 * 128 * 2)  // This may be incorrect. Try dividing total again by 2
#define strideD0I 1    // Standard strides only
#define strideC0I 1
#define strideAL 1
#define strideBL 1

extern "C" __global__ void __launch_bounds__(NUM_THREADS)
fp16_GEMM_128x128x16_(
  tensile_half *D,
  tensile_half const * C,
  tensile_half const * A,
  tensile_half const * B,
  float const alpha,
  float const beta,
  unsigned int const strideD1J,
  unsigned int const strideDK,
  unsigned int const strideC1J,
  unsigned int const strideCK,
  unsigned int const strideA0I,
  unsigned int const strideAK,
  unsigned int const strideB1J,
  unsigned int const strideBK,
  unsigned int size0I,
  unsigned int size1J,
  unsigned int sizeK,
  unsigned int sizeL,
  unsigned int staggerUIterParm,
  unsigned int problemNumGroupTiles0,
  unsigned int problemNumGroupTiles1 )
{
  // LDS allocation
  __shared__ tensile_half lds[LDS_SIZE / sizeof(tensile_half)];

  /* ============ Workgroup Thread Indexing  ======= */
  // Wavefront-local IDs (0-15 in I/J)
  uint32_t tidI = threadIdx.x % SG0I;  // 0-15 in I
  uint32_t tidJ = threadIdx.x / SG0I;  // 0-15 in J

  // Workgroup IDs (tile positions)
  uint32_t wgM = blockIdx.x * MT0I;    // Starting row
  uint32_t wgN = blockIdx.y * MT1J;    // Starting col

  // Global thread IDs (absolute matrix positions)
  uint32_t globalM = wgM + tidI;
  uint32_t globalN = wgN + tidJ;

  /* ============== Bounds Checking  ================ */
  // Check if thread is within matrix bounds
  bool inBoundsM = (globalM < size0I);
  bool inBoundsN = (globalN < size1J);

  // Initialize accumulator registers (64 elements for 8x8 microtiles)
  float acc[TT0I * TT1J] = {0};  // Use FP32 for accumulation

  /* =========== Minimal Main Loop Example ========= */
  // Iterate over K in chunks (using LDS)
  for (uint32_t kBase = 0; kBase < sizeK; kBase += MT0I) {
    uint32_t kEnd = min(kBase + MT0I, sizeK);
    uint32_t kChunk = kEnd - kBase;

    // Load A into LDS (simplified coalesced load)
    if (tidI < MT0I && tidJ < kChunk) {
      uint32_t aIdx = (wgM + tidI) * strideA0I + (kBase + tidJ) * strideAK;
      lds[tidI * MT0I + tidJ] = (inBoundsM && (kBase + tidJ < sizeK)) ? A[aIdx] : 0;
    }

    // Load B into LDS (transposed for coalescing)
    if (tidI < kChunk && tidJ < MT1J) {
      uint32_t bIdx = (kBase + tidI) * strideBK + (wgN + tidJ) * strideB1J;
      lds[MT0I * MT0I + tidJ * MT0I + tidI] = (inBoundsN && (kBase + tidI < sizeK)) ? B[bIdx] : 0;
    }
    __syncthreads();

    // Main MAC Loop
    for (uint32_t k = 0; k < kChunk; k += UNROLL) {
      #pragma unroll
      for (int u = 0; u < UNROLL; ++u) {
        uint32_t kVal = k + u;
        if (kVal < kChunk) {
          // Load micro-tile of A (from LDS)
          tensile_half aReg[TT0I];
          for (int i = 0; i < TT0I; ++i) {
            aReg[i] = lds[(tidI * TT0I + i) * MT0I + kVal];
          }

          // Load micro-tile of B (from LDS, transposed)
          tensile_half bReg[TT1J];
          for (int j = 0; j < TT1J; ++j) {
            bReg[j] = lds[MT0I * MT0I + (tidJ * TT1J + j) * MT0I + kVal];
          }

          // Multiply-add into accumulator
          for (int i = 0; i < TT0I; ++i) {
            for (int j = 0; j < TT1J; ++j) {
              acc[i * TT1J + j] += (float)aReg[i] * (float)bReg[j];
            }
          }
        }
      }
    }
    __syncthreads();
  }


  /* ============== Epilogue writes  ========== */
  // Apply alpha and write D
  if (inBoundsM && inBoundsN) {
    uint32_t dIdx = globalM * strideD0I + globalN * strideD1J;
    uint cIdx = globalM * strideC0I + globalN * strideC1J;
    for (int i = 0; i < TT0I; ++i) {
      for (int j = 0; j < TT1J; ++j) {
        if ((globalM + i < size0I) && (globalN + j < size1J)) {
          D[dIdx + i * strideD0I + j * strideD1J] = (tensile_half)(alpha * acc[i * TT1J + j]) + (beta * (float)C[cIdx]);
        }
      }
    }
  }

}
```
The only caveat is that LDS_SIZE (shared memory) calculation.  i don't remember if that is correct or not.  it's a minor thing anyways, and the correct math should take into account how LDS is split for the double-buffering optimization that most Tensile kernels default to (and the compute data type, which is fp16 in this case).  You can add in some code for bank conflict avoidance (like StaggerU, or XOR swizzle) to make it complete.

For other kernels the LDS must be transposed differently or not at all, depending on the particular contraction you're working with.  Remove some of the flashy comments if the LLM you use doesn't have much context length.  Moonshot's Kimi 1 trillion parameter LLM model seems to sometimes prefer those flashy type comments, maybe.  Good luck, and take care

**Comment by advanced-lvl-up** [comment]
And here's the more complete version with less comments that will actually compile and run:  This follows more to the actual syntax that tensile will output.

```
#define NUM_THREADS 256
#define SG0I 16
#define SG1J 16
#define TT0I 8
#define TT1J 8
#define MT0I (SG0I * TT0I) // 128
#define MT1J (SG1J * TT1J) // 128
#define LDS_OFFSET_B 4096    // split LDS for buffering
#define LDS_ELEMENTS 8192
#define VECTOR_WIDTH 8
#define LOCAL_SPLITU 1
#define UNROLL 32
#define LOCAL_DEPTHU (LOCAL_SPLITU * UNROLL) // 32
#define CPSV (NUM_THREADS / MT0I * VECTOR_WIDTH)

#define NLCA 2
#define NLCB 2
#define LSCA (LOCAL_DEPTHU / NLCA) // 16
#define LSCB (LOCAL_DEPTHU / NLCB) // 16
#define LVCA (LSCA / VECTOR_WIDTH) // 2
#define LVCB (LSCB / VECTOR_WIDTH) // 2

#define DATA_TYPE tensile_half
#define GLOBAL_OFFSET_A(idxL, idx0I, idxK) (( (idxL)*1 + (idx0I)*strideA0I + (idxK)*strideAK ))
#define GLOBAL_OFFSET_B(idxL, idx1J, idxK) (( (idxL)*1 + (idx1J)*strideB1J + (idxK)*strideBK ))

extern "C" __global__ void __launch_bounds__(256) fp16_gemm(
    DATA_TYPE *D, DATA_TYPE const *C,
    DATA_TYPE const *A, DATA_TYPE const *B,
    uint sizeM, uint sizeN, uint sizeK, uint batchL,
    uint strideA0I, uint strideB1J, uint strideAK, uint strideBK) {

  tensile_half rC[64] = { 0 }; //  registers for MAC's 
  tensile_half rA[16]; // divide by 2 for double-buffering
  tensile_half rB[16]; // divide by 2 for double-buffering
  __shared__ DATA_TYPE localMemory[8192];

  // address registers for global to local 
  DATA_TYPE a_vals[2][8];
  DATA_TYPE b_vals[2][8];

  unsigned int thread = threadIdx.x;
  unsigned int sgId = thread / (SG0I*SG1J);
  unsigned int wg0I = blockIdx.x;
  unsigned int wg1J = blockIdx.y;
  unsigned int wgK = blockIdx.z % sizeK;

  // local read addresses: final offsets
  unsigned int localReadOffsetA = (thread % SG0I)* 8 + sgId*(MT0I);
  unsigned int localReadOffsetB = ((thread / SG0I) % SG1J) * 8 + sgId * (MT1J) + 4096;

  // local read addresses: declare addresses
  DATA_TYPE *localReadA;
  DATA_TYPE *localReadB;

  // global read addresses: tile offset assignments
  unsigned int globalReadOffsetA0I = (thread / LVCA) + (wg0I) * MT0I;
  unsigned int globalReadOffsetB1J = (thread / LVCB) + (wg1J) * MT1J;

  // global read addresses: unroll assignments
  unsigned int globalReadOffsetAL = (thread % LVCA) * VECTOR_WIDTH;
  unsigned int globalReadOffsetBL = (thread % LVCB )* VECTOR_WIDTH;

  // global read addresses: final offsets
  int64_t globalReadOffsetA0 = GLOBAL_OFFSET_A( globalReadOffsetAL, globalReadOffsetA0I, wgK );
  int64_t globalReadOffsetA1 = GLOBAL_OFFSET_A( globalReadOffsetAL + LSCA, globalReadOffsetA0I, wgK );
  int64_t globalReadOffsetB0 = GLOBAL_OFFSET_B( globalReadOffsetBL, globalReadOffsetB1J, wgK );
  int64_t globalReadOffsetB1 = GLOBAL_OFFSET_B( globalReadOffsetBL + LSCB, globalReadOffsetB1J, wgK );

  // global read addresses: addresses
  DATA_TYPE const *globalReadA00 = A + globalReadOffsetA0;
  DATA_TYPE const *globalReadA10 = A + globalReadOffsetA1;
  DATA_TYPE const *globalReadB00 = B + globalReadOffsetB0;
  DATA_TYPE const *globalReadB10 = B + globalReadOffsetB1;

  // global read addresses: increments
  int64_t globalReadIncAL = 32;
  int64_t globalReadIncBL = 32;

  // local write addresses: tile assignments
  uint lwA0I = thread / LVCA;
  uint lwB1J = thread / LVCB;

  // local write addresses: unroll assignment
  uint lwAL = (thread % LVCA) * VECTOR_WIDTH;
  uint lwBL = (thread % LVCB) * VECTOR_WIDTH;

  uint ldsWriteOffsetA = lwA0I + lwAL*MT0I;
  uint ldsWriteOffsetB = lwB1J + lwBL*MT1J + LDS_OFFSET_B;

  DATA_TYPE *writeA[2][8], *writeB[2][8];
  for (int load = 0; load < 2; load++) {
      for (int step = 0; step < 8; step++) {
          uint offsetA = ldsWriteOffsetA + (step + load*LSCA)*MT0I;
          uint offsetB = ldsWriteOffsetB + (step + load*LSCB)*MT1J;
          writeA[load][step] = localMemory + offsetA;
          writeB[load][step] = localMemory + offsetB;
      }
  }

  int numIterL = batchL / LOCAL_DEPTHU;

  localReadA = localMemory + localReadOffsetA;
  localReadB = localMemory + localReadOffsetB;

  // Main unroll loop begins
  while (numIterL-- > 0) {

    const DATA_TYPE* globalReadA[2] = {globalReadA00, globalReadA10};
    const DATA_TYPE* globalReadB[2] = {globalReadB00, globalReadB10};
    for (int u = 0; u < 2; u++) {
        __syncthreads(); 
        for (int v = 0; v < 8; v++) {
            a_vals[u][v] = globalReadA[u][v];
            b_vals[u][v] = globalReadB[u][v];
        }
    }

    // global read increments for sum L
    globalReadA00 += globalReadIncAL;
    globalReadA10 += globalReadIncAL;
    globalReadB00 += globalReadIncBL;
    globalReadB10 += globalReadIncBL;

    __syncthreads(); 

    // write local addresses
    for (int u = 0; u < 2; u++) {
        for (int v = 0; v < 8; v++) {
            *writeA[u][v] = a_vals[u][v];
            *writeB[u][v] = b_vals[u][v];
        }
    }

    __syncthreads(); //

    // Preload a tile
    for (int i = 0; i < 8; ++i) {
        rA[i] = localReadA[i];
        rB[i] = localReadB[i];
    }
    localReadA += 128;
    localReadB += 128;

    for (int iter = 0; iter < 15; ++iter) {
        for (int i = 0; i < 8; ++i) {
            rA[i+8] = localReadA[i];
            rB[i+8] = localReadB[i];
        }
        for (int b = 0; b < 8; ++b) {        
            for (int a = 0; a < 8; ++a) {
                rC[b * 8 + a] += rA[a] * rB[b];    // MAC_8x8 for tileA
            }
        }
        localReadA += 128;
        localReadB += 128;

        for (int i = 0; i < 8; ++i) {
            rA[i] = localReadA[i];
            rB[i] = localReadB[i];
        }
        for (int b = 0; b < 8; ++b) {         
            for (int a = 0; a < 8; ++a) {
                rC[b * 8 + a] += rA[a+8] * rB[b+8];    //  MAC_8x8 for tileB offset 8
            }
        }
        localReadA += 128;
        localReadB += 128;

    }

    // Process remaining tiles
    for (int i = 0; i < 8; ++i) {
        rA[i+8] = localReadA[i];
        rB[i+8] = localReadB[i];
    }
    for (int b = 0; b < 8; ++b) {
        for (int a = 0; a < 8; ++a) {
            rC[b * 8 + a] += rA[a] * rB[b];
        }
    }

    for (int b = 0; b < 8; ++b) {
        for (int a = 0; a < 8; ++a) {
            rC[b * 8 + a] += rA[a+8] * rB[b+8];
        }
    }

    // Reset pointers for next iteration
  localReadA = localMemory + localReadOffsetA;
  localReadB = localMemory + localReadOffsetB;

  }

  uint flatGlobalC0 = (wg0I)*MT0I + (thread % SG0I)*VECTOR_WIDTH;
  uint flatGlobalC1 = (wg1J)*MT1J + (thread / SG0I)*VECTOR_WIDTH;
  uint globalCK = (wgK);

  uint32_t baseD = GLOBAL_D(flatGlobalC0, flatGlobalC1, globalCK);
  uint32_t baseC = GLOBAL_C(flatGlobalC0, flatGlobalC1, globalCK);

  for (uint32_t jj = 0; jj < 8; ++jj) {
      for (uint32_t ii = 0; ii < 8; ++ii) {
            uint32_t rCIndex = ii + jj * 8;
            uint32_t i = i0 + ii;
            uint32_t j = j0 + jj;
            if (i < sizeM && j < sizeN) {
            uint32_t dIdx = baseD + ii * strideD0I + jj * strideD1J;
                uint32_t cIdx = baseC + ii * strideC0I + jj * strideC1J;
                D[dIdx] = (beta != 0) ? alpha * rC[rCIndex] + beta * C[cIdx] : alpha * rC[rCIndex];
            }
        }
    }
}
```

**Comment by chboishabba** [comment]
https://github.com/chboishabba/gfx803_compat_graph

**Comment by chboishabba** [comment]
<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/67f71c30-fc6b-4109-a191-088e777ed3dc" />


produced with sd (via nix -> vk build)  via https://github.com/chboishabba/gfx803_compat_graph

I've started adding runners/graph etc for community members to assist

**Comment by chboishabba** [comment]
@tuleo1 you may want to try nix flakes provided above, I wasn't able to reproduce your error. Perhaps they will assist in isolating the variable... 
EDIT:  repeated_inference_drift FAILED as non-deterministic. 
EDIT: The Result
6 out of 7 diffusion tests passed — FP32, FP16, mixed precision, 50-step, large channels, and timing stability all clean. But 

repeated_inference_drift
 failed as non-deterministic: the same model with the same input gives different outputs across runs.

Why This Matters
This perfectly explains the community's confusion. tuleo1 reports:

"basic math is fine... GroupNorm, SiLU, attention work without NaN" → matches our 8/8 basic probe pass
"once it comes to ComfyUI suddenly all I get is noise" → non-deterministic kernel selection accumulates drift over 20+ diffusion steps
"MIOpen perfdb sometimes faster, sometimes slower, can't reproduce 2.6s/it" → the perfdb is non-deterministic on gfx803
The Root Cause Theory
MIOpen's performance database selects different Tensile kernel variants across runs. On gfx803, these kernels have varying precision characteristics (HH types are fast but noisy, SS types crash, BB types are correct but slow). When MIOpen picks different kernels on different runs, each step has slightly different precision behaviour. Over 20-50 diffusion steps, these tiny differences (~1e-5) accumulate into visible noise.

EDIT: Winograd seemed to have a direct impact, triggering the kfd reset on 6.19 cachy

**Comment by chboishabba** [comment]
My probes revealed that while individual kernels (GEMM, Direct) are often deterministic when run in isolation on a fresh process, high-volume kernel switching or context accumulation poisons the GPU state.

In a targeted stress test, I observed a standard 1x1 Convolution (normally rock-solid) produce a massive output difference of 0.98 (absolute failure) after just a few hundred preceding kernel launches.

Refined Findings & Root Causes
Winograd/FFT (Hang Source): Confirmed as the primary cause of system hangs. Disabling them preserves system stability but doesn't fix all the math.
Einsum/Attention (Noise Source): Highly non-deterministic by default. Successfully fixed with torch.use_deterministic_algorithms(True) and CUBLAS_WORKSPACE_CONFIG.
Solver Flapping (Corruption Source): The massive diffs (~1.6 to 3.6) we saw in the UNet bisection occur when MIOpen switches solvers or context under pressure. 1x1 convolutions and large Deconvs (ConvTranspose2d) are most susceptible.
Environment Sync: I found that MIOPEN_DEBUG_... environment variables are sometimes ignored if set after the MIOpen context is initialized. They must be exported before the process starts or very early in the script.

Suggested actions:
```
# System/Driver Flags
export HSA_OVERRIDE_GFX_VERSION=8.0.3
export MIOPEN_LOG_LEVEL=3
export ROC_ENABLE_PRE_VEGA=1

# Math/Solvers
export MIOPEN_DEBUG_CONV_WINOGRAD=0     # Prevent hangs
export MIOPEN_DEBUG_CONV_FFT=0          # Extra safety
export MIOPEN_DEBUG_CONV_DET=1          # Attempt deterministic selection
export CUBLAS_WORKSPACE_CONFIG=:4096:8  # Required for deterministic matmul

# MIOpen Cleanup (Crucial for fresh state)
export MIOPEN_DEBUG_DISABLE_FIND_DB=1   # Prevent using stale/buggy cached solvers
export MIOPEN_FIND_ENFORCE=3            # Force MIOpen to pick one and stick to it
```

EDIT:

I've completed the deep-dive validation using a high-intensity "hook-based" diagnostic. I have identified the exact bit-perfect frontier for your RX 580.

### The Final Diagnosis: "The Polaris Residual"

My tests confirmed that even with every known stability flag enabled, a full UNet loop on Polaris (gfx803) has a residual non-determinism of **~0.02 - 0.04**. 

*   **The Good News:** This is a **100x improvement** over the previous state (where we saw errors of 1.6 to 3.6). A drift of 0.02 is visually imperceptible in image generation—it won't cause the "exploding noise" or black artifacts you were seeing.
*   **The Hardware Reality:** This residual drift is likely a driver/compiler limitation in how ROCm 6.4 handles atomic accumulation on Polaris hardware. It is a "known-unknown" that we have mitigated as far as current software allows.

### Your "Stable Profile" Commands

To run your workflows with maximum stability, use the following configurations.

#### Option A: Maximum Performance (Recommended)
Use this for daily ComfyUI/Whisper use. It prevents hangs and fixes the major noise bugs.
```bash
docker run --rm \
    -e HSA_OVERRIDE_GFX_VERSION=8.0.3 \
    -e MIOPEN_DEBUG_CONV_WINOGRAD=0 \
    -e MIOPEN_DEBUG_CONV_FFT=0 \
    -e CUBLAS_WORKSPACE_CONFIG=:4096:8 \
    --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host \
    itir:latest # or your target image
```

#### Option B: Maximum Precision (Experimental)
Use this if you still see artifacts or need the absolute most reproducible results. Note: This will be ~2x slower as it bypasses MIOpen's tuned kernels.
```bash
docker run --rm \
    -e HSA_OVERRIDE_GFX_VERSION=8.0.3 \
    -e MIOPEN_DEBUG_CONV_WINOGRAD=0 \
    -e CUBLAS_WORKSPACE_CONFIG=:4096:8 \
    --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host \
    itir:latest python3 -c "import torch; torch.backends.cudnn.enabled=False; torch.use_deterministic_algorithms(True); # start_your_app()"
```

### Final Documentation
I have updated your brain with the finalized [POLARIS_STABILITY_BLUEPRINT.md](file:///home/c/.gemini/antigravity/brain/45b160db-c113-423b-9984-07a61a39f466/POLARIS_STABILITY_BLUEPRINT.md). It contains the full technical breakdown, the "Poison State" reproduction logs, and the recommended flags for different workloads (ComfyUI vs WhisperX).


🔍 Analysis of your Profiler Trace
Your rocprof output confirms the root cause of the residual drift:

The Culprit: The rocBLAS GEMM kernel Cijk_Ailk_Bljk_SB_MT64x64x16..._ISA803.
The Bug: This kernel is mathematically incorrect. Because it's a Tensile-generated kernel specifically for ISA803, the bug is likely in the Tensile YAML configurations or the assembly generator for Polaris.
The Verification: Since your Direct Only run (ID 85) showed zero drift, we now know for a fact that the Direct path is safe, while the GEMM path is corrupted.
🚀 Recommended Path for Submission
You now have enough evidence to submit three separate (but related) issues:

MIOpen: Ring timeouts with Winograd on GFX803.
MIOpen: Incorrect solver fallback selection (GemmFwdRest chosen over Direct despite the drift).
Tensile/rocBLAS: The specific MT64x64x16..._ISA803 kernel produces incorrect results.

**Comment by chboishabba** [comment]
Backtesting against rocm 5.7

**Comment by advanced-lvl-up** [comment]
> Backtesting against rocm 5.7

@chboishabba did you guys ever get `llama-cpp-python` working in Linux ROCm?  for example, to integrate ComfyUI style workflows with LLMs and such.

some of the better LLM and vision models only require `transformers==4.57.0` or higher, and can work without even installing llama.

Edit:  i found this database that might help, in case anyone is having issues.  He says it's specifically for Ubuntu/Debian, though.
https://huggingface.co/datasets/AIencoder/llama-cpp-wheels
I don't know anything about this, myself.  Just some random info.

**Comment by chboishabba** [comment]
https://hub.docker.com/u/robertrosenbusch

Yes there are prepared roc 6.4.3 containers for whisperx, ollama, and comfui (as well as pytorch and base) which are also ubuntu based. They can still sometimes trigger hard reset/freeze and presumably that kernel drift I mentioned above might be causing noisy outputs under some circumstances (seems to depend which kernel gets selected at runtime)...
Just checked and looks like ollama one is running 4.52.4
EDIT:
🛡️ Phase 1 Complete: The "Nix Blockade" is Broken
The core reason your Nix host environment outright rejected the GPU wasn't drivers; it was ABI gatekeeping in the latest libhsa-runtime64 (ROCm 7.2) which actively refuses to spin up Polaris. We managed to bypass this by completely untangling the ROCm 6.4 userspace stack from the Docker container and wiring it directly to your host's Nix environment via 

scripts/extract-docker-libs.sh
 and 

scripts/polaris-env.sh
.

You can now run any Polaris ML workload natively on the host just by sourcing that script. No Docker required.

🎯 Phase 2 Complete: The Target is Locked
By running the 

run-drift-matrix
 with the newly liberated host environment, we produced the explicit proof we needed:

json
{ "case": "direct_only", "drift": 0 }
{ "case": "gemm_only", "drift": 0.152567 }
The 0 drift confirms it: The GPU's hardware and driver behave flawlessly when running the source-based (LLVM-compiled) Direct solvers. The 0.15 drift confirms that the GemmFwdRest assembly kernels constructed by Tensile are the root cause. This is either Tensile generating incorrect assembly instructions for gfx803 or a weird edge case inside rocBLAS.

We now have the raw data that developers need to debug the kernel generator.

**Comment by advanced-lvl-up** [comment]
understood,  i've been curious about that.  Here's a temporary fix that doesn't require Ollama or ROCm. 

Spent 5 hours testing this excellent fork of `llama.cpp`and highly recommend it to anyone.  This will work for any OS or hardware!
https://github.com/JamePeng/llama-cpp-python
it's quite different, as it's a bindings wrapper that installs directly inside a pytorch style VENV or stand-alone VENV.  Hence, it should be easier for testing and integration.  This method doesn't require running `Ollama server on port: your IP`, for example.  It will just be part of the GUI.

you can also mix and match by using Vulkan for the LLM part, and ROCm for the rest of the workflow, (all inside ComfyUI).  In fact, you don't need to install Comfy at all.  Just execute a plain `.py` script you get from Claude or Gemini if you really want to.

Prompt: Describe the words inside this image using only Hiragana and Kanji.  Your main task is translation to Japanese. 
Qwen3VL's Answer:
<img width="1332" height="630" alt="Image" src="https://github.com/user-attachments/assets/2e74cdb5-d999-440a-b904-ac0629eb1f9a" />

Google translate of Qwen's output:
_"This image depicts a wooden storage box containing an old recipe notebook. Handwritten text is visible at the top of the notebook, outlining a recipe for pumpkin pie with entries such as "One 9-inch pie," "Pumpkin Pie," "3/4 cup brown sugar," "1 lb. flour," and "1/4 tsp. salt." Affixed to the side of the box is a red label bearing the word "Cookie," likely suggesting that the box also houses other cookie recipes. The box features a design with a white background, framed by wavy yellow and blue lines, and adorned in the center with a floral motif in red and blue. The surface of the box bears marks of wear and deterioration from use, testifying to its age and history of handling. The handwritten text is penned in blue ballpoint ink, and the handwriting style exhibits the distinctive characteristics of a personal, handwritten recipe. In the background of the image, a section of the white shelf upon which the storage box rests is visible."_

Wow, Qwen3VL 4b is super good. I'm shocked that it got the "1 Lbs. flour" part correct.  Her handwriting is confusing.  Wait, i'm still not sure. haha. (link for the custom node used in the test: https://github.com/huchukato/ComfyUI-QwenVL-Mod)

**System Required**: CPU with at least 12 gigabytes of system DRAM. (16 to 32 gigabytes recommended). 
**Pytorch**:  Optional but recommended.  CPU Pytorch is fine for testing,  Use ROCm Pytorch if it works for you.
**ComfyUI**: Optional, recommended.  The GUI and integrated workflows are nice.
**GPU**: Optional.  Try Vulkan first with at least 4gb VRAM GPU.

1. goto the official Vulkan homepage and get the SDK.  https://vulkan.lunarg.com/doc/sdk/latest/linux/getting_started.html
2. activate your Comfy venv, and follow the intructions here https://github.com/JamePeng/llama-cpp-python
3. Make sure your CMAKE_ARGS are set correctly. if Vulkan doesn't compile, just use CPU mode (its fine for 4b parameters).
(for CPU only, try the following with all CMAKE_ARGS removed / empty)
`pip install "llama-cpp-python @ git+https://github.com/JamePeng/llama-cpp-python.git"`
4. load Comfy and the custom node.  That should be all.  Good luck.

set `ctx` (Context length) to 1536.  (16384 or max context will double or quadruple the memory requirements without FlashAttn).
set `gpu_layers` at about 20 to 25 should be fine for 4GB VRAM (4 Billion parameter Qwen3VL LLM model will use 3.5gb VRAM.)
set `gpu_layers` at about 30 to 50 for 8GB VRAM.  You'll need to add quant and KV settings to run 8 billion parameters or higher.
set `max_tokens` from about 128 to 512, depending on how much text you want the LLM output.
set `n_batch` (number of batches) to about 512 or so.  Lower uses less VRAM, higher uses more

On an unrelated note: I also tried the Qwen3.5 (27billion parameter multimodal, GGUF quant IQ2_M) using ONLY CPU and system DRAM.  Super slow on my potato PC. The perplexity score at GGUF IQ2_M was impressive.  (For something that big, it's better to stay with Kobold.cpp or similar where you have extra KV caching and quantization options on startup.)  Have fun & safe travels.

**Comment by chboishabba** [comment]
https://github.com/chboishabba/gfx803_compat_graph/blob/master/docs/USER_GUIDE.md

This provides a guide to use nix for running working gfx803 compatibility layer without the heavier addition of a full container.

**Comment by tuleo1** [comment]
@chboishabba  love your repo btw! i just checked it and i see a lot of intresting work happening
love the work youre putting on to this and i might onme and check it out
although idk how nix and stuff work and im on arch rn so idk lol
maybe ill put a virtual machine with vfio and put nix in it?
perhaps.

**Comment by chboishabba** [comment]
> [@chboishabba](https://github.com/chboishabba) love your repo btw! i just checked it and i see a lot of intresting work happening love the work youre putting on to this and i might onme and check it out although idk how nix and stuff work and im on arch rn so idk lol maybe ill put a virtual machine with vfio and put nix in it? perhaps.

https://github.com/chboishabba/gfx803_compat_graph/pull/2
welcome to give that a try. i'm using nix inside arch at the moment. tested working with whisperx and comfy.

Seems like it will still hit kfd reset under the right conditions, but am making progress nailing this down. I have it at a working point so lost incentive to keep pushing but would appreciate others' help/contributions. At the moment my main fix for those running into this is to run your process with blocking/sync enabled. Unfortunately this seems to dramatically affect tps and CPU but I don't htink I have confirmed this with tests. The other thing you can do is just try to relieve memory pressure if possible.

Basically what seems to happen is that newer kfd has stronger reset/async/memory semantics which gfx803 doesn't support at least at the moment. Host seeks invalid device memory -> reset -> fail to recover -> glitch screen/black.

End goal was to have some way to be able to use system kfd/torch compiled/patched/hosted from the nix.

Also the patched torch/whisper/comfy from robert's dockerfiles have been kindly hosted by Cachix so do not require recompilation/downloading the whole dockers.

I think the main thing I ran into is that sometimes you need to provide icd path? not sure if i'm misremembering that.
